# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a5e83807e3731f3ac54ed22f246b31a3c31f9dece77ce2662d489e6614f59629891d1d1dcd954943e68f9437f57594b593c4ad464d51ca6a16fba3f9ed2466f

test:
  secret_key_base: 91271b4923cdf8642d7e20ab4b7f31138304ca77defdcb982af495b6b2203d5ec2f960e2072ebcd5e1c9e95d3e5e558c1c7dfabd715446660d44fbee3b63b554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
